version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
      - redis

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   # Vite dev server
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
      - sink

  sink:
    build:
      context: ./sink
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  seed:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run seeds
    env_file: .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data: